// <auto-generated />
using CRUDAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDAPI.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaId"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            Idade = 50,
                            Nome = "Robson",
                            Profissao = "Programador",
                            Sobrenome = "O Programador"
                        },
                        new
                        {
                            PessoaId = 2,
                            Idade = 48,
                            Nome = "Rosângela",
                            Profissao = "Secretária",
                            Sobrenome = "A Secretária da Academia"
                        },
                        new
                        {
                            PessoaId = 3,
                            Idade = 26,
                            Nome = "Roberta",
                            Profissao = "Vendedora",
                            Sobrenome = "Pode Chamar de Beta"
                        },
                        new
                        {
                            PessoaId = 4,
                            Idade = 9,
                            Nome = "Nick",
                            Profissao = "Cachorro",
                            Sobrenome = "The Dog"
                        },
                        new
                        {
                            PessoaId = 5,
                            Idade = 40,
                            Nome = "Severino",
                            Profissao = "Faz Tudo",
                            Sobrenome = "O Faz Tudo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
